version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dardos
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: blog
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
